/**
 * Standardized error codes for the API.
 */
export const ErrorCodes = {
  // Authentication
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  AUTH_CSRF_INVALID: 'AUTH_CSRF_INVALID',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_EMAIL_INVALID: 'VALIDATION_EMAIL_INVALID',
  VALIDATION_FIELD_REQUIRED: 'VALIDATION_FIELD_REQUIRED',
  VALIDATION_FILE_TOO_LARGE: 'VALIDATION_FILE_TOO_LARGE',
  VALIDATION_FILE_TYPE_INVALID: 'VALIDATION_FILE_TYPE_INVALID',

  // Import
  IMPORT_NOT_FOUND: 'IMPORT_NOT_FOUND',
  IMPORT_ALREADY_PROCESSING: 'IMPORT_ALREADY_PROCESSING',
  IMPORT_CANCELLED: 'IMPORT_CANCELLED',
  IMPORT_CSV_PARSE_ERROR: 'IMPORT_CSV_PARSE_ERROR',
  IMPORT_COLUMN_MAPPING_REQUIRED: 'IMPORT_COLUMN_MAPPING_REQUIRED',

  // Lead
  LEAD_NOT_FOUND: 'LEAD_NOT_FOUND',
  LEAD_DUPLICATE: 'LEAD_DUPLICATE',
  LEAD_SUPPRESSED: 'LEAD_SUPPRESSED',

  // Campaign
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  CAMPAIGN_NOT_EDITABLE: 'CAMPAIGN_NOT_EDITABLE',
  CAMPAIGN_NO_RECIPIENTS: 'CAMPAIGN_NO_RECIPIENTS',
  CAMPAIGN_ALREADY_RUNNING: 'CAMPAIGN_ALREADY_RUNNING',
  CAMPAIGN_PAUSED: 'CAMPAIGN_PAUSED',
  CAMPAIGN_LIMIT_REACHED: 'CAMPAIGN_LIMIT_REACHED',

  // AI
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_RATE_LIMITED: 'AI_RATE_LIMITED',
  AI_RESPONSE_INVALID: 'AI_RESPONSE_INVALID',
  AI_TIMEOUT: 'AI_TIMEOUT',

  // Email
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  EMAIL_ALREADY_SENT: 'EMAIL_ALREADY_SENT',
  EMAIL_RECIPIENT_SUPPRESSED: 'EMAIL_RECIPIENT_SUPPRESSED',
  EMAIL_DAILY_LIMIT_REACHED: 'EMAIL_DAILY_LIMIT_REACHED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

  // Webhook
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_DUPLICATE_EVENT: 'WEBHOOK_DUPLICATE_EVENT',
  WEBHOOK_PROCESSING_FAILED: 'WEBHOOK_PROCESSING_FAILED',

  // Suppression
  SUPPRESSION_ALREADY_EXISTS: 'SUPPRESSION_ALREADY_EXISTS',
  SUPPRESSION_NOT_FOUND: 'SUPPRESSION_NOT_FOUND',

  // General
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMITED: 'RATE_LIMITED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  REDIS_ERROR: 'REDIS_ERROR',
} as const;

/** ErrorCode as a const object — use ErrorCode.XXX for runtime values */
export const ErrorCode = ErrorCodes;

/** ErrorCode as a type — use for type annotations */
export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
